### ISSUE TITLE
Envie seu artigo

### ISSUE THREAD

**Issue by alexandrevicenzi** [ButecoOpenSource/butecoopensource.github.io#1]
Que tal ter um artigo publicado no [butecopensource.org](http://www.butecopensource.org)?

Envie seu artigo relacionado a tecnologia e ainda participe do Hacktoberfest.

Entre em contato conosco através do [Slack](https://buteco-slack.herokuapp.com/).

**Comment by luisslanca** [comment]
Olá Alexandre, estou começando agora a mexer com o Git. O objetivo da issue seria fazer um commit .md de um artigo sobre tecnologia escrito por mim?

**Comment by alexandrevicenzi** [comment]
@luisslanca o objetivo é escrever um artigo estilo o quais escrevemos.

Como usamos Jekyll o artigo deve ser escrito preferenciamente em Markdown, em ultimos casos pode ser escrito em HTML.

Para mandar um PR ou commit você precisa fazer um fork do projeto.

**Comment by luisslanca** [comment]
@alexandrevicenzi consegui fazer. Qualquer erro me comunique por favor. Obrigado
